project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Wine Quality Prediction"

format:
  html:
    theme:
      light: cosmo
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
